input {
  file {
    path => "/logs/app.log"
    start_position => "beginning"
    codec => "json"
  }
}

filter {
  mutate {
    add_field => { "pipeline" => "fastapi-structlog" }
  }
}

output {
  stdout { codec => rubydebug }

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "fastapi-logs-%{+YYYY.MM.dd}"
  }
}


